### PR TITLE
Replace deprecated RessourceManager with ProjectsClient

### PR DESCRIPTION
**Pull request by clementdenis**
Also fix some warnings

---
This change is [Reviewable](https://reviewable.io/reviews/aodocs/endpoints-authenticators/14)

### CODE REVIEW

**Review by RaHery — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-authenticators/14)* status: all files reviewed, 3 unresolved discussions (waiting on @clementdenis)

___
*[src/main/java/com/aodocs/endpoints/auth/AuthInfo.java, line 42 at r1](https://reviewable.io/reviews/aodocs/endpoints-authenticators/14#-MkLCP9i5fjH7QjLXdqq:-MkLCP9i5fjH7QjLXdqr:b-sam9wc) ([raw file](https://github.com/aodocs/endpoints-authenticators/blob/54e1cdb870bf099eb567b895d0cee1374134543c/src/main/java/com/aodocs/endpoints/auth/AuthInfo.java#L42)):*
> ```Java
> public class AuthInfo {
> 
>     AuthType authType;
> ```

Why removing `private`?
___
*[src/main/java/com/aodocs/endpoints/auth/authorizers/Authorizer.java, line 34 at r1](https://reviewable.io/reviews/aodocs/endpoints-authenticators/14#-MkLC9039a3D-7XQ_LWd:-MkLC9039a3D-7XQ_LWe:b60b048) ([raw file](https://github.com/aodocs/endpoints-authenticators/blob/54e1cdb870bf099eb567b895d0cee1374134543c/src/main/java/com/aodocs/endpoints/auth/authorizers/Authorizer.java#L34)):*
> ```Java
>   @Value
>   @Builder
>   class AuthorizationResult {
> ```

Why removing the `final` ?
___
*[src/main/java/com/aodocs/endpoints/context/ProjectConfigProvider.java, line 128 at r1](https://reviewable.io/reviews/aodocs/endpoints-authenticators/14#-MkLBDbE7w2R7DH8bj5i:-MkLBDbE7w2R7DH8bj5j:ba7htsd) ([raw file](https://github.com/aodocs/endpoints-authenticators/blob/54e1cdb870bf099eb567b895d0cee1374134543c/src/main/java/com/aodocs/endpoints/context/ProjectConfigProvider.java#L128)):*
> ```Java
>     }
> 
> 	private final ProjectsClient projectsClient;
> ```

Is it safe to keep this as a field of the class ? This is a closeable resource, and you close it at every usage so that only the first call would work and close the resource ; subsequent calls may fail since it is already closed ...

**Review by clementdenis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-authenticators/14)* status: all files reviewed, 3 unresolved discussions (waiting on @RaHery)

___
*[src/main/java/com/aodocs/endpoints/auth/AuthInfo.java, line 42 at r1](https://reviewable.io/reviews/aodocs/endpoints-authenticators/14#-MkLCP9i5fjH7QjLXdqq:-MkLUiw78DU3c4efKrQd:butac88) ([raw file](https://github.com/aodocs/endpoints-authenticators/blob/54e1cdb870bf099eb567b895d0cee1374134543c/src/main/java/com/aodocs/endpoints/auth/AuthInfo.java#L42)):*
<details><summary><i>Previously, RaHery (Hermann RANGAMANA) wrote…</i></summary><blockquote>

Why removing `private`?
</blockquote></details>

Because it's redundant with @Value (too bad Reviewable does not show it :-))
___
*[src/main/java/com/aodocs/endpoints/auth/authorizers/Authorizer.java, line 34 at r1](https://reviewable.io/reviews/aodocs/endpoints-authenticators/14#-MkLC9039a3D-7XQ_LWd:-MkLUsonB1Bc8ZAjR0xJ:b-3dytg2) ([raw file](https://github.com/aodocs/endpoints-authenticators/blob/54e1cdb870bf099eb567b895d0cee1374134543c/src/main/java/com/aodocs/endpoints/auth/authorizers/Authorizer.java#L34)):*
<details><summary><i>Previously, RaHery (Hermann RANGAMANA) wrote…</i></summary><blockquote>

Why removing the `final` ?
</blockquote></details>

Because it's redundant with @Value
___
*[src/main/java/com/aodocs/endpoints/context/ProjectConfigProvider.java, line 128 at r1](https://reviewable.io/reviews/aodocs/endpoints-authenticators/14#-MkLBDbE7w2R7DH8bj5i:-MkLV-hM4W028Rfb9eIH:b3rs9j1) ([raw file](https://github.com/aodocs/endpoints-authenticators/blob/54e1cdb870bf099eb567b895d0cee1374134543c/src/main/java/com/aodocs/endpoints/context/ProjectConfigProvider.java#L128)):*
<details><summary><i>Previously, RaHery (Hermann RANGAMANA) wrote…</i></summary><blockquote>

Is it safe to keep this as a field of the class ? This is a closeable resource, and you close it at every usage so that only the first call would work and close the resource ; subsequent calls may fail since it is already closed ...
</blockquote></details>

Indeed, that's not ideal ... but it's needed for testing.
Anyway, I'll replace it with a Supplier to make it safer.

**Review by clementdenis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-authenticators/14)* status: all files reviewed, 3 unresolved discussions (waiting on @RaHery)

___
*[src/main/java/com/aodocs/endpoints/context/ProjectConfigProvider.java, line 128 at r1](https://reviewable.io/reviews/aodocs/endpoints-authenticators/14#-MkLBDbE7w2R7DH8bj5i:-MkLWrLEEzC_SyEw7K1T:b-896fix) ([raw file](https://github.com/aodocs/endpoints-authenticators/blob/54e1cdb870bf099eb567b895d0cee1374134543c/src/main/java/com/aodocs/endpoints/context/ProjectConfigProvider.java#L128)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

Indeed, that's not ideal ... but it's needed for testing.
Anyway, I'll replace it with a Supplier to make it safer.
</blockquote></details>

Done.

**Review by RaHery — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-authenticators/14#-:-MkLwco8DVz9O5MB2uAj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @clementdenis)

**Pull request merged**
