### PR TITLE
Add new authorizer: CurrentProjectAudienceAuthorizer

### PR DESCRIPTION
**Pull request by RaHery**
This change is [Reviewable](https://reviewable.io/reviews/aodocs/endpoints-authenticators/13)

### CODE REVIEW

**Review by clementdenis — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-authenticators/13)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaHery)

___
*[src/main/java/com/aodocs/endpoints/auth/authorizers/audience/CurrentProjectAudienceAuthorizer.java, line 34 at r1](https://reviewable.io/reviews/aodocs/endpoints-authenticators/13#-MkCdf1kBcgvtnyWT7gR:-MkCdf1kBcgvtnyWT7gS:b2ri0p) ([raw file](https://github.com/aodocs/endpoints-authenticators/blob/91eccdbcc01d756e6123f8af922244ddc6869c40/src/main/java/com/aodocs/endpoints/auth/authorizers/audience/CurrentProjectAudienceAuthorizer.java#L34)):*
> ```Java
> import com.google.cloud.resourcemanager.Project;
> 
> @Slf4j
> ```

Not useful, as we don't have any log in this class

**Review by RaHery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-authenticators/13)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @clementdenis)

___
*[src/main/java/com/aodocs/endpoints/auth/authorizers/audience/CurrentProjectAudienceAuthorizer.java, line 34 at r1](https://reviewable.io/reviews/aodocs/endpoints-authenticators/13#-MkCdf1kBcgvtnyWT7gR:-MkGzZyD5V7rGR3kwYC8:b-896fix) ([raw file](https://github.com/aodocs/endpoints-authenticators/blob/91eccdbcc01d756e6123f8af922244ddc6869c40/src/main/java/com/aodocs/endpoints/auth/authorizers/audience/CurrentProjectAudienceAuthorizer.java#L34)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

Not useful, as we don't have any log in this class
</blockquote></details>

Done.

**Review by clementdenis — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-authenticators/13)* status: all files reviewed, 1 unresolved discussion (waiting on @RaHery)

___
*[src/main/java/com/aodocs/endpoints/auth/authorizers/audience/CurrentProjectAudienceAuthorizer.java, line 37 at r2](https://reviewable.io/reviews/aodocs/endpoints-authenticators/13#-MkH0FCj4nTXXvBf41hU:-MkH0FCj4nTXXvBf41hV:bh5zrz5) ([raw file](https://github.com/aodocs/endpoints-authenticators/blob/b39ed6bb7e27d640f70c1cd5a632c35b86e27a65/src/main/java/com/aodocs/endpoints/auth/authorizers/audience/CurrentProjectAudienceAuthorizer.java#L37)):*
> ```Java
> 		String projectId = ProjectConfigProvider.get().getProject().getProjectId();
> 		List<String> audience = extendedUser.getAudience();
> 		return newResultBuilder().authorized(audience != null && audience.contains(projectId)).build();
> ```

I did not see it in the first pass, but it is VERY wrong :-)

if audience=ao-docs-dev and projectId=ao-docs, the user will be authorized, which is not expected => should be a strict equality

**Review by RaHery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-authenticators/13)* status: all files reviewed, 1 unresolved discussion (waiting on @clementdenis)

___
*[src/main/java/com/aodocs/endpoints/auth/authorizers/audience/CurrentProjectAudienceAuthorizer.java, line 37 at r2](https://reviewable.io/reviews/aodocs/endpoints-authenticators/13#-MkH0FCj4nTXXvBf41hU:-MkHThll3TjplwvAMsJg:b-3t0fpj) ([raw file](https://github.com/aodocs/endpoints-authenticators/blob/b39ed6bb7e27d640f70c1cd5a632c35b86e27a65/src/main/java/com/aodocs/endpoints/auth/authorizers/audience/CurrentProjectAudienceAuthorizer.java#L37)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

I did not see it in the first pass, but it is VERY wrong :-)

if audience=ao-docs-dev and projectId=ao-docs, the user will be authorized, which is not expected => should be a strict equality
</blockquote></details>

It is already a strict equality because `audience` is a list, not a string :)

**Review by clementdenis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-authenticators/13)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaHery)

___
*[src/main/java/com/aodocs/endpoints/auth/authorizers/audience/CurrentProjectAudienceAuthorizer.java, line 37 at r2](https://reviewable.io/reviews/aodocs/endpoints-authenticators/13#-MkH0FCj4nTXXvBf41hU:-MkHWsJG9WYdYE8z8YDW:b1i9den) ([raw file](https://github.com/aodocs/endpoints-authenticators/blob/b39ed6bb7e27d640f70c1cd5a632c35b86e27a65/src/main/java/com/aodocs/endpoints/auth/authorizers/audience/CurrentProjectAudienceAuthorizer.java#L37)):*
<details><summary><i>Previously, RaHery (Hermann RANGAMANA) wrote…</i></summary><blockquote>

It is already a strict equality because `audience` is a list, not a string :)
</blockquote></details>

My bad!!

BTW, we had the discussion with the Hungarian team on why the audience field is a list in the code, while it's returned as a simple string in the JWT tokens we get.
=> The RFC is a bit weird on this, both string and list of string are OK
https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3

**Review by clementdenis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-authenticators/13#-:-MkHXRmM4if0IbZpusIc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaHery)

**Pull request merged**
