### PR TITLE
Offer generic method to query claims in JWT token

### PR DESCRIPTION
**Pull request by RaHery**
I barely move up codes that extract claims using jsonp notation from `JwtClaimsAuthorizer` into `AuthInfo` so that it is available for other usages.

---
This change is [Reviewable](https://reviewable.io/reviews/aodocs/endpoints-authenticators/17)

### CODE REVIEW

**Review by clementdenis — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-authenticators/17)* status: all files reviewed, 2 unresolved discussions (waiting on @RaHery)

___
*[src/main/java/com/aodocs/endpoints/auth/AuthInfo.java, line 106 at r1](https://reviewable.io/reviews/aodocs/endpoints-authenticators/17#-MtwZpq-DjjwTSEEu6t2:-MtwZpq-DjjwTSEEu6t3:b-7ojjt3) ([raw file](https://github.com/aodocs/endpoints-authenticators/blob/b99a44a7728d6538953e5ae8260658f5fda29211/src/main/java/com/aodocs/endpoints/auth/AuthInfo.java#L106)):*
> ```Java
>                             new Object[] {key, nodeType, node});
>             }
>             return Optional.empty();
> ```

You lost some part of the logic here:
- Previously, unsupported node types would always return a false claim check, even if the value to compare it with was null
- Now, if you try to compare an unsupported node type with the null value, the check will succeed
=> you could fix this by returning null in the last return, and checking nullness of the value (making the Optional a tristate value)
___
*[src/main/java/com/aodocs/endpoints/auth/authorizers/token/JwtClaimsAuthorizer.java, line 90 at r1](https://reviewable.io/reviews/aodocs/endpoints-authenticators/17#-Mtw_EZx9PsuW0aoKxRm:-Mtw_EZx9PsuW0aoKxRn:b-bxoxv6) ([raw file](https://github.com/aodocs/endpoints-authenticators/blob/b99a44a7728d6538953e5ae8260658f5fda29211/src/main/java/com/aodocs/endpoints/auth/authorizers/token/JwtClaimsAuthorizer.java#L90)):*
> ```Java
>         return claims.get(key)
>                 .map(claimValue -> Objects.equals(claimValue, value))
>                 .orElse(value == null);
> ```

See previous comment: some logic is lost for unsupported node types because of this last check.
=> Claims.get should return a null on unsupported node type and you should check nullness first.

**Review by clementdenis — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-authenticators/17)* status: all files reviewed, 2 unresolved discussions (waiting on @RaHery)

___
*[src/main/java/com/aodocs/endpoints/auth/AuthInfo.java, line 106 at r1](https://reviewable.io/reviews/aodocs/endpoints-authenticators/17#-MtwZpq-DjjwTSEEu6t2:-Mtw_vUE7pqa7rW7DM1u:b-wrvch0) ([raw file](https://github.com/aodocs/endpoints-authenticators/blob/b99a44a7728d6538953e5ae8260658f5fda29211/src/main/java/com/aodocs/endpoints/auth/AuthInfo.java#L106)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

You lost some part of the logic here:
- Previously, unsupported node types would always return a false claim check, even if the value to compare it with was null
- Now, if you try to compare an unsupported node type with the null value, the check will succeed
=> you could fix this by returning null in the last return, and checking nullness of the value (making the Optional a tristate value)
</blockquote></details>

BTW, this means I initially forgot a unit test for this case :)

**Review by RaHery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-authenticators/17)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @clementdenis)

___
*[src/main/java/com/aodocs/endpoints/auth/AuthInfo.java, line 106 at r1](https://reviewable.io/reviews/aodocs/endpoints-authenticators/17#-MtwZpq-DjjwTSEEu6t2:-MtwyT1OCgoCX8MtqUbL:b-d1c0h3) ([raw file](https://github.com/aodocs/endpoints-authenticators/blob/b99a44a7728d6538953e5ae8260658f5fda29211/src/main/java/com/aodocs/endpoints/auth/AuthInfo.java#L106)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

BTW, this means I initially forgot a unit test for this case :)
</blockquote></details>

You are right!
Done.
___
*[src/main/java/com/aodocs/endpoints/auth/authorizers/token/JwtClaimsAuthorizer.java, line 90 at r1](https://reviewable.io/reviews/aodocs/endpoints-authenticators/17#-Mtw_EZx9PsuW0aoKxRm:-MtwyXHD0YCYGgbNAf68:b-896fix) ([raw file](https://github.com/aodocs/endpoints-authenticators/blob/b99a44a7728d6538953e5ae8260658f5fda29211/src/main/java/com/aodocs/endpoints/auth/authorizers/token/JwtClaimsAuthorizer.java#L90)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

See previous comment: some logic is lost for unsupported node types because of this last check.
=> Claims.get should return a null on unsupported node type and you should check nullness first.
</blockquote></details>

Done.

**Review by clementdenis — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-authenticators/17)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaHery)

**Review by clementdenis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-authenticators/17#-:-MtxA3Nt-dT2OPHoVpb4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaHery)

**Review by clementdenis — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-authenticators/17)* status: all files reviewed, 1 unresolved discussion (waiting on @RaHery)

___
*[src/main/java/com/aodocs/endpoints/auth/AuthInfo.java, line 35 at r2](https://reviewable.io/reviews/aodocs/endpoints-authenticators/17#-MtxDJYe8ZnBPEpkb4x2:-MtxDJYe8ZnBPEpkb4x3:b-tqtvlh) ([raw file](https://github.com/aodocs/endpoints-authenticators/blob/2776adaee3f4618718245b3e5483fe325fab50ac/src/main/java/com/aodocs/endpoints/auth/AuthInfo.java#L35)):*
> ```Java
> 
> import org.apache.commons.lang3.StringUtils;
> import org.checkerframework.checker.nullness.qual.Nullable;
> ```

This is not used.

**Review by RaHery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-authenticators/17)* status: all files reviewed, 1 unresolved discussion (waiting on @clementdenis)

___
*[src/main/java/com/aodocs/endpoints/auth/AuthInfo.java, line 35 at r2](https://reviewable.io/reviews/aodocs/endpoints-authenticators/17#-MtxDJYe8ZnBPEpkb4x2:-MtxFFEN0zhvENTEAbXA:b-896fix) ([raw file](https://github.com/aodocs/endpoints-authenticators/blob/2776adaee3f4618718245b3e5483fe325fab50ac/src/main/java/com/aodocs/endpoints/auth/AuthInfo.java#L35)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

This is not used.
</blockquote></details>

Done.

**Review by RaHery — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-authenticators/17#-:-MuKkg-836_pNPjKzkLo:bnfp4nl)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @clementdenis)

**Review by clementdenis — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-authenticators/17#-:-MuKw3Lz5gjsNzay6y_m:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaHery)

**Pull request merged**
